#!/usr/bin/env sh

export ND_BASEURL="${NAVIDROME__BASEURL:-/}"
export ND_COVERARTPRIORITY="${NAVIDROME__COVERARTPRIORITY}"
export ND_DEFAULTLANGUAGE="${NAVIDROME__DEFAULTLANGUAGE:-en}"
export ND_DEFAULTTHEME="${NAVIDROME__DEFAULTTHEME}"
export ND_LOGLEVEL="${NAVIDROME__LOGLEVEL:-info}"
export ND_PROMETHEUS_ENABLED="${NAVIDROME__PROMETHEUS_ENABLED:-false}"
export ND_REVERSEPROXYUSERHEADER="${NAVIDROME__REVERSEPROXYUSERHEADER:-Remote-User}"
export ND_REVERSEPROXYWHITELIST="${NAVIDROME__REVERSEPROXYWHITELIST}"

exec "$@"
