#!/usr/bin/env sh

export DATABASE_URL="postgresql://${MINIFLUX__POSTGRES_USERNAME}:${MINIFLUX__POSTGRES_PASSWORD}@${MINIFLUX__POSTGRES_HOST}:${MINIFLUX__POSTGRES_PORT:-5432}/${MINIFLUX__POSTGRES_DATABASE}?sslmode=${MINIFLUX__POSTGRES_SSLMODE:-require}"
export RUN_MIGRATIONS="${MINIFLUX__RUN_MIGRATIONS:-1}"

export ADMIN_PASSWORD="${MINIFLUX__ADMIN_PASSWORD}"
export ADMIN_USERNAME="${MINIFLUX__ADMIN_USERNAME}"
export CREATE_ADMIN="${MINIFLUX__CREATE_ADMIN}"

export AUTH_PROXY_HEADER="${MINIFLUX__AUTH_PROXY_HEADER:-Remote-User}"
export AUTH_PROXY_USER_CREATION="${MINIFLUX__AUTH_PROXY_USER_CREATION}"

export BASE_URL="${MINIFLUX__BASE_URL:-http://localhost}"
export DEBUG="${MINIFLUX__DEBUG}"

export INVIDIOUS_INSTANCE="${MINIFLUX__INVIDIOUS_INSTANCE}"
export POCKET_CONSUMER_KEY="${MINIFLUX__POCKET_CONSUMER_KEY}"

export METRICS_ALLOWED_NETWORKS="${MINIFLUX__METRICS_ALLOWED_NETWORKS:-127.0.0.1/8}"
export METRICS_COLLECTOR="${MINIFLUX__METRICS_COLLECTOR}"

export POLLING_FREQUENCY="${MINIFLUX__POLLING_FREQUENCY:-60}"
export POLLING_PARSING_ERROR_LIMIT="${MINIFLUX__POLLING_PARSING_ERROR_LIMIT:-5}"

exec "$@"
